[package]
name = "cellpool-coordinator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
cellpool-proofs = { path = "../proofs", default-features = true }
derivative = "2.2.0"
serde = "1.0.151"
serde_json = "1.0.91"
serde_with = { version = "2.1.0", features = ["hex"] }
